chainweb:
  payloadProviders:
    chain-0:
      type: pact
    chain-1:
      type: pact
    chain-10:
      type: pact
    chain-11:
      type: pact
    chain-12:
      type: pact
    chain-13:
      type: pact
    chain-14:
      type: pact
    chain-15:
      type: pact
    chain-16:
      type: pact
    chain-17:
      type: pact
    chain-18:
      type: pact
    chain-19:
      type: pact
    chain-2:
      type: pact
    chain-20:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://bootnode-evm-20:8551/
      type: evm
    chain-21:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://bootnode-evm-21:8551/
      type: evm
    chain-22:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://bootnode-evm-22:8551/
      type: evm
    chain-23:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://bootnode-evm-23:8551/
      type: evm
    chain-24:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://bootnode-evm-24:8551/
      type: evm
    chain-3:
      type: pact
    chain-4:
      type: pact
    chain-5:
      type: pact
    chain-6:
      type: pact
    chain-7:
      type: pact
    chain-8:
      type: pact
    chain-9:
      type: pact
    default:
      redeemAccount: '0xd42d71cdc2A0a78fE7fBE7236c19925f62C442bA'
      redeemChain: 0
