#!/bin/bash

# Compose action (remaining arguments from 4th onward)
compose_action="-v --remove-orphans"

source ./scripts/commands/stop "$@"

delete_network_if_exists proxy-network
delete_network_if_exists service-network