#!/bin/bash
source ./scripts/utils/init_chain_vars.sh "$@"

compose_action="--pull=missing"

echo "Starting using: docker compose up -d $compose_action"

create_network_if_missing proxy-network
create_network_if_missing service-network

sleep 2

run "docker compose -p bs_general -f general-docker-compose.yaml up -d $compose_action"  

sleep 5

for ((i = 0; i < numberOfChains; i++)); do
  chainId=$((i + $chainIdOffset))
  chainWebChainId=$((i + $chainwebChainIdOffset))
  run "CHAIN_ID=$chainId CHAINWEB_CHAIN_ID=$chainWebChainId docker compose -p bs_chain_${chainWebChainId} --env-file ./envs/chain-common.env -f common-docker-compose.yaml up -d $compose_action"
done

run "docker compose -p bs_gateway -f gateway-docker-compose.yaml up -d $compose_action"  

info "Blockscout started successfully."

for ((i = 0; i < numberOfChains; i++)); do
  chainId=$((i + $chainIdOffset))
  chainWebChainId=$((i + $chainwebChainIdOffset))
  echo "chain $chainWebChainId": "http://chain-$chainWebChainId.${BASE_EXPLORER_DOMAIN}:${BASE_GATEWAY_PUBLIC_PORT}"
done

info "Run './bs add-domains' to add domains to /etc/hosts"
