#!/bin/bash
source ./scripts/utils/init_chain_vars.sh "$@"

compose_action="-d"  

run "docker compose -p bs_general -f general-docker-compose.yaml up $compose_action"  

for ((i = start; i <= end; i++)); do
  run "CHAIN_ID=$((i + 1789)) CHAINWEB_CHAIN_ID=$i docker compose -p bs_chain_${i} --env-file ./envs/chain-common.env -f common-docker-compose.yaml up $compose_action"
done

run "docker compose -p bs_gateway -f gateway-docker-compose.yaml up $compose_action"  

