/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KDA__factory } from "./KDA__factory";
export { SimpleToken__factory } from "./SimpleToken__factory";
