services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_INGRESS_NETWORKS=proxy-network
      # - BASE_EXPLORER_DOMAIN=${BASE_EXPLORER_DOMAIN}  # Add domain variable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      # - "${BASE_GATEWAY_PUBLIC_PORT:-80}:80"
      # - "443:443"  # Add HTTPS port
      # - "8080:8080"
      # - "8081:8081"
    healthcheck:
      disable: true
    networks:
      - proxy-network
    labels:
      caddy.debug: ""
      caddy.email: "test@test.com"
    #   # Main domain routing
    #   caddy: ${BASE_EXPLORER_DOMAIN}
    #   caddy.reverse_proxy: http://proxy:80
      
    #   # Stats endpoint
    #   caddy_1: ${BASE_EXPLORER_DOMAIN}:8080
    #   caddy_1.reverse_proxy: http://stats:8050
      
    #   # Visualizer endpoint
    #   caddy_2: ${BASE_EXPLORER_DOMAIN}:8081
    #   caddy_2.reverse_proxy: http://visualizer:8081
      
    #   # Automatic HTTPS configuration
      # caddy.tls: internal
      # caddy.auto_https: disable_redirects
