services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_INGRESS_NETWORKS=proxy-network
      # - BASE_EXPLORER_DOMAIN=${BASE_EXPLORER_DOMAIN}  # Add domain variable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # adding for debugging purposes 
      # no config needs to be provided, it will be overwritten by the labels
      - ./caddy_data:/config
    healthcheck:
      disable: true
    networks:
      - proxy-network
    labels:
      caddy.email: ${BASE_SUPPORT_EMAIL}
