services:
  frontend:
    image: ghcr.io/kadena-io/blockscout-frontend:main
    # image: ghcr.io/blockscout/frontend:latest
    extra_hosts:
      - 'chain-${CHAINWEB_CHAIN_ID}.${BASE_EXPLORER_DOMAIN}:host-gateway'
    platform: linux/amd64
    pull_policy: always
    restart: always
    env_file:
      -  ../envs/common-frontend.env
