services:
  frontend:
    image: ghcr.io/kadena-io/blockscout-frontend:${FRONTEND_DOCKER_TAG:-sha-0549c821f038fedc0d5c9301d5d750fae127b4d4}
    platform: linux/amd64
    pull_policy: always
    restart: always
    env_file:
      -  ../envs/common-frontend.env
