chainweb:
  payloadProviders:
    chain-1:
      type: pact
    chain-19:
      type: pact
    chain-20:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://appdev-evm-20:8551/
      type: evm
    chain-24:
      engineJwtSecret: 10b45e8907ab12dd750f688733e73cf433afadfd2f270e5b75a6b8fff22dd352
      engineUri: http://appdev-evm-24:8551/
      type: evm
    chain-5:
      type: pact
    default:
      redeemAccount: '0xd42d71cdc2A0a78fE7fBE7236c19925f62C442bA'
      redeemChain: 0
