#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"


if [ ! -f $(pwd)/.env ]; then
  echo ".env file not found. use the .env.example file to create it."
  exit 1
fi

# Export base environment variables
set -a
. $(pwd)/.env
set +a

source ./scripts/utils/utils.sh

blockscout-help() {
  echo -e "Commands:"
  echo -e "  ${B}pull${R}               pull container images for all blockscout services."
  echo -e "  ${B}start|up${R}           Start the blockscout with specified parameters. used pull images or pull if not available."
  echo -e "  ${B}stop|down${R}          Stop the blockscout."
  echo -e "  ${B}remove|delete${R}      Remove the blockscout data."
  echo -e "  ${B}add-domains${R}        Add domains to the host."
  echo -e "  ${B}static-envs${R}        create static environment variables files"
  echo -e "  ${B}restart <service>${R}  restart the specified service. valid services are: frontend, backend, stats, user-ops-indexer, proxy"
  echo -e ""
  echo -e "Environment variables:"
  echo -e "  The script loads .env file from the current directory. You can use the .env.example.* file to create it."
  echo -e "  ${B}BASE_CHAIN_ID_OFFSET${R}           The chain ID of the first chain"
  echo -e "  ${B}BASE_CHAINWEB_CHAIN_ID_OFFSET${R}  The chainweb chain ID of the first chain"
  echo -e "  ${B}BASE_NUMBER_OF_CHAINS${R}          number of chains"
  echo -e "  ${B}BASE_EXPLORER_DOMAIN${R}           The domain of the blockscout explorer."
  echo -e "  ${B}BASE_GATEWAY_PUBLIC_PORT${R}       The public port of the gateway"
  echo -e "  ${B}BASE_CHAINWEB_NODE_PUBLIC_URL${R}  The public URL of the chainweb node."
  echo -e "  ${B}BASE_JSONRPC_HTTP_URL${R}          The base url of JSON-RPC of chains for HTTP requests."
  echo -e "  ${B}BASE_JSONRPC_WS_URL${R}            The base url of JSON-RPC of chains for WS requests."
  echo -e ""
}

# Check if at least one argument is passed
if [ $# -lt 1 ]; then
  blockscout-help
  exit 1
fi

# Get the first argument as command
cmd="$1"
shift  # Remove the first argument so $@ is the rest

command_dir="./scripts/commands"

case "$cmd" in
  start|up)
    $command_dir/start "$@"
    ;;
  stop|down)
    $command_dir/stop "$@"
    ;;
  pull)
    $command_dir/pull "$@"
    ;;  
  remove|delete)
    $command_dir/remove "$@"
    ;;
  add-domains)
    $command_dir/add-domains "$@"
    ;;
  static-envs)
    $command_dir/static-envs "$@"
    ;;
  help|usage|h)
    blockscout-help
    ;;
  restart)
    $command_dir/restart "$@"
    ;;    
  *)
    blockscout-help
    exit 1
    ;;
esac
