#!/bin/bash
source ./scripts/utils/utils.sh

# Check if at least one argument is passed
if [ $# -lt 1 ]; then
  echo "Usage: $0 {start|stop|remove|add-domains|static-envs} <chian_id_offset (default=1789)> <chainweb_chain_id_offset (default=20)> <number_of_chains (default=5)>"
  echo ""
  echo "Examples:"
  info "Start with default values:"
  echo "$0 start "
  info "Start with 2 chains"
  echo "$0 start 1789 20 2"
  info "Start with specific chain ID offset 1234 and 2 chains"
  echo "$0 start 1234 20 2"
  exit 1
fi

# Get the first argument as command
cmd="$1"
shift  # Remove the first argument so $@ is the rest

command_dir="./scripts/commands"

case "$cmd" in
  start)
    $command_dir/start "$@"
    ;;
  stop)
    $command_dir/stop "$@"
    ;;
  remove)
    $command_dir/remove "$@"
    ;;
  add-domains)
    $command_dir/add-domains "$@"
    ;;
  static-envs)
    $command_dir/static-envs "$@"
    ;;
  *)
    echo "Unknown command: $cmd"
    echo "Usage: $0 {start|stop|remove} [args...]"
    exit 1
    ;;
esac