#!/bin/bash

compose_action="${*}"

run() {
  local cmd="$*"
  echo ""
  echo "$cmd"
  echo "========================================="
  eval "$cmd"
}


run "docker compose -p bs_general -f general-docker-compose.yaml up -d $compose_action"  


for i in {20..24}; do
  run "CHAIN_ID=$((i + 1789)) CHAINWEB_CHAIN_ID=$i docker compose -p bs_chain_${i} --env-file ./envs/chain-common.env -f common-docker-compose.yaml up -d $compose_action"
done


run "docker compose -p bs_gateway -f gateway-docker-compose.yaml up -d $compose_action"  

