volumes:
  redis-data:
  logs:
  dets:

networks:
  default:
    driver: bridge

  proxy-network:
    external: true
    name: proxy-network  

  service-network:
    external: true
    name: service-network

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    networks:
      - default   
      

  create-blockscout-db:
    extends:
      file: ./services/create-db.yml
      service: create-blockscout-db
    networks:
      - service-network  

  create-stats-db:
    extends:
      file: ./services/create-db.yml
      service: create-stats-db
    networks:
      - service-network     

      

  backend:
    depends_on:
      redis-db:
        condition: service_started
      create-blockscout-db : 
          condition: service_completed_successfully  
    extends:
      file: ./services/backend.yml
      service: backend   
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - SUBNETWORK=${SUBNETWORK}
      - ETHEREUM_JSONRPC_HTTP_URL=${ETHEREUM_JSONRPC_HTTP_URL}
      - ETHEREUM_JSONRPC_WS_URL=${ETHEREUM_JSONRPC_WS_URL}
      - ETHEREUM_JSONRPC_TRACE_URL=${ETHEREUM_JSONRPC_TRACE_URL}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - service-network 
      - default     

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    volumes:
      - ./logs/frontend:/app/logs
      - ./assets:/assets
    environment:
      - NEXT_PUBLIC_NETWORK_ID=${NEXT_PUBLIC_NETWORK_ID?}

      # Kinda sucks. Why does this communicate via the host network? 
      # I think because this urls will be used in the browser so they should target the host not the container
      - NEXT_PUBLIC_STATS_API_HOST=${NEXT_PUBLIC_STATS_API_HOST}
      - NEXT_PUBLIC_VISUALIZE_API_HOST=${NEXT_PUBLIC_VISUALIZE_API_HOST}
      - NEXT_PUBLIC_APP_HOST=${NEXT_PUBLIC_APP_HOST}
      - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT}
      - NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}
      - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT}
      - NEXT_PUBLIC_NETWORK_NAME=${NEXT_PUBLIC_NETWORK_NAME}
      - NEXT_PUBLIC_NETWORK_RPC_URL=${NEXT_PUBLIC_NETWORK_RPC_URL}
      - NEXT_PUBLIC_FEATURED_NETWORKS=${NEXT_PUBLIC_FEATURED_NETWORKS}
    networks:
      - default   


  stats:
    depends_on:
      backend:
        condition: service_started
      create-stats-db : 
          condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
      - service-network 
      - default      

  user-ops-indexer:
    depends_on:
      backend:
        condition: service_started
      create-blockscout-db : 
          condition: service_completed_successfully
      create-stats-db : 
          condition: service_completed_successfully    
    restart: on-failure      
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    environment:
      - USER_OPS_INDEXER__INDEXER__RPC_URL=${USER_OPS_INDEXER__INDEXER__RPC_URL}
      - USER_OPS_INDEXER__DATABASE__CONNECT__URL=${USER_OPS_INDEXER__DATABASE__CONNECT__URL}  
    networks:
      - service-network  
      - default  
 
  
  proxy:
    restart: on-failure
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
     - default    
     - proxy-network

