#!/bin/bash

compose_action="${*}"

echo "Stopping using: 'docker compose down $compose_action'"

echo ""
echo "Stopping gateway containers..."
echo "==============================="
docker compose -p bs_gateway  -f gateway-docker-compose.yaml down $compose_action

for i in {20..24}; do
  echo "Starting chain $i ..."
  echo "=============================="
  export CHAIN_ID=$((i + 1789))
  export CHAINWEB_CHAIN_ID=$i 
  docker compose -p bs_chain_${i} \
    --env-file ./envs/chain-common.env \
    -f common-docker-compose.yaml down $compose_action
  echo ""
done


echo ""
echo "Stopping general containers..."
echo "==============================="
docker compose -p bs_general  -f general-docker-compose.yaml down $compose_action