volumes:
  blockscout-db-data:
  stats-db-data:

services:
  db-init:
    extends:
      file: ./services/databases.yml
      service: db-init
    networks:
      - service-network

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/databases.yml
      service: db
    networks:
      - service-network

  stats-db-init:
    extends:
      file: ./services/databases.yml
      service: stats-db-init
    networks:
      - service-network

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/databases.yml
      service: stats-db
    networks:
      - service-network

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      - proxy-network
    labels:
      caddy: http://${BASE_EXPLORER_DOMAIN}
      caddy.handle_path: "/visualizer/*"
      caddy.handle_path.0_rewrite: "* {uri}"
      caddy.handle_path.reverse_proxy: "{{ upstreams 8050 }}"
      # caddy.handle_path.@allowed_origins: "header Origin *chain-*.evm.kadena.internal"
      # caddy.handle_path.1_header: "@allowed_origins Access-Control-Allow-Origin '{http.header.Origin}'"
      # caddy.handle_path.2_header: "@allowed_origins Access-Control-Allow-Methods 'GET, POST, OPTIONS'"
      # caddy.handle_path.3_header: "@allowed_origins Access-Control-Allow-Headers '*'"
      # caddy.handle_path.0_header: "@allowed_origins Access-Control-Allow-Credentials 'true'"
      
      # caddy_0: http://chain-21.${BASE_EXPLORER_DOMAIN}
      # caddy_0.handle_path: "/visualizer/*"
      # caddy_0.handle_path.0_rewrite: "* {uri}"
      # caddy_0.handle_path.reverse_proxy: "{{ upstreams 8050 }}"

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
      - service-network

  smart-contract-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    ports:
      - '4000:8050'
    networks:
      - service-network
      - proxy-network

  proxy:
    extends:
      file: ./services/caddy-gateway.yml
      service: proxy
    ports:
      - '${BASE_GATEWAY_PUBLIC_PORT:-8000}:80'
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    driver: bridge

  service-network:
    name: service-network
    driver: bridge
