volumes:
  blockscout-db-data:
  stats-db-data:

services:
  db-init:
    extends:
      file: ./services/databases.yml
      service: db-init
    networks:
      - service-network  

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/databases.yml
      service: db
    networks:
      - service-network  

  stats-db-init:
    extends:
      file: ./services/databases.yml
      service: stats-db-init
    networks:
      - service-network  


  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/databases.yml
      service: stats-db
    networks:
      - service-network  

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      - proxy-network   

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
      - service-network          

  smart-contract-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    networks:
      - service-network       



networks:
  proxy-network:
    external: true
    name: proxy-network  

  service-network:
    external: true
    name: service-network
  


