#!/bin/bash

echo ""
echo "Stopping gateway containers..."
echo "==============================="
docker compose -p bs_gateway  -f gateway-docker-compose.yaml down -v --remove-orphans

echo ""
echo "Stopping chain 0 containers..."
echo "=============================="
docker compose -p bs_chain_0  --env-file ./envs/chain-0.env  --env-file ./envs/chain-common.env -f common-docker-compose.yaml down -v --remove-orphans

echo ""
echo "Stopping chain 1 containers..."
echo "=============================="
docker compose -p bs_chain_1  --env-file ./envs/chain-1.env  --env-file ./envs/chain-common.env -f common-docker-compose.yaml down -v --remove-orphans

echo ""
echo "Stopping general containers..."
echo "==============================="
docker compose -p bs_general  -f general-docker-compose.yaml down -v --remove-orphans