#!/bin/bash
echo ""
echo "Starting chain 0 ..."
echo "=============================="
docker compose -p bs_chain_20  --env-file ./envs/chain-0.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d

echo ""
echo "Starting chain 1 ..."
echo "=============================="
docker compose -p bs_chain_21  --env-file ./envs/chain-1.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d



echo ""
echo "Starting chain 2 ..."
echo "=============================="
docker compose -p bs_chain_22  --env-file ./envs/chain-2.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d


echo ""
echo "Starting chain 3 ..."
echo "=============================="
docker compose -p bs_chain_23  --env-file ./envs/chain-3.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d


echo ""
echo "Starting chain 4 ..."
echo "=============================="
docker compose -p bs_chain_24  --env-file ./envs/chain-4.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d