#!/bin/bash
echo ""
echo "Starting chain 0 ..."
echo "=============================="
docker compose -p bs_chain_0  --env-file ./envs/chain-0.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d

echo ""
echo "Starting chain 1 ..."
echo "=============================="
docker compose -p bs_chain_1  --env-file ./envs/chain-1.env  --env-file ./envs/chain-common.env  -f common-docker-compose.yaml up -d