#!/bin/bash
echo ""
echo "/Stopping chain 0 containers..."
echo "=============================="
docker compose -p bs_chain_0  --env-file ./envs/chain-0.env --env-file ./envs/chain-common.env -f common-docker-compose.yaml down

echo ""
echo "Stopping chain 1 containers..."
echo "=============================="
docker compose -p bs_chain_1  --env-file ./envs/chain-1.env --env-file ./envs/chain-common.env -f common-docker-compose.yaml down