#!/bin/bash

echo ""
echo "Stopping chain 0 containers..."
echo "=============================="
docker compose -p bs-chain-0  --env-file ./envs/chain-0.env -f common-docker-compose.yaml down

echo ""
echo "Stopping chain 1 containers..."
echo "=============================="
docker compose -p bs-chain-1  --env-file ./envs/chain-1.env -f common-docker-compose.yaml down

echo ""
echo "Stopping database containers..."
echo "==============================="
docker compose -p bs-database  -f db-docker-compose.yaml down  