#!/bin/bash

echo ""
echo "Stopping gateway proxy..."
echo "==============================="
docker compose -p bs_gateway  -f gateway-docker-compose.yaml down 

./stop-chains

echo ""
echo "Stopping general containers..."
echo "==============================="
docker compose -p bs_general  -f general-docker-compose.yaml down 