name: Test Devnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.GITHUB_TOKEN }}

      - name: Start Devnet
        working-directory: ./devnet
        run: |
          docker compose up -d
          # Wait for devnet to be ready
          sleep 30

      - name: Run Tests
        working-directory: ./tests
        run: |
          bun install
          bun run test

      - name: Cleanup
        if: always()
        run: |
        # I am unsure this is needed as this VM will delete after use
          ./network devnet stop
